### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by ipsod** [MrYsLab/telemetrix-esp32#3]
```
  File "/home/zero/rockbox/gk/robots/TheBees/client/venv/lib/python3.10/site-packages/telemetrix_aio_esp32/ble_aio_transport.py", line 110, in connect
    except bleak.exc.BleakDBusError:
NameError: name 'bleak' is not defined

```

Fixed this by adding `import bleak` at the top of the file, then I got this error:

```
Traceback (most recent call last):
  File "/home/zero/rockbox/gk/robots/TheBees/client/the_bees.py", line 140, in <module>
    board = MKSTinyBee(
  File "/home/zero/rockbox/gk/robots/TheBees/client/the_bees.py", line 95, in __init__
    super().__init__(*args, **kwargs)
  File "/home/zero/rockbox/gk/robots/TheBees/client/venv/lib/python3.10/site-packages/t
elemetrix_aio_esp32/telemetrix_aio_esp32.py", line 254, in __init__
    self.loop.run_until_complete(self.start_aio())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/zero/rockbox/gk/robots/TheBees/client/venv/lib/python3.10/site-packages/t
elemetrix_aio_esp32/telemetrix_aio_esp32.py", line 278, in start_aio
    await self.transport.connect()
  File "/home/zero/rockbox/gk/robots/TheBees/client/venv/lib/python3.10/site-packages/t
elemetrix_aio_esp32/ble_aio_transport.py", line 109, in connect
    await self.client.connect()
  File "/home/zero/rockbox/gk/robots/TheBees/client/venv/lib/python3.10/site-packages/b
leak/backends/bluezdbus/client.py", line 107, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/home/zero/rockbox/gk/robots/TheBees/client/venv/lib/python3.10/site-packages/b
leak/backends/scanner.py", line 220, in find_device_by_address
    device_identifier = device_identifier.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

```

I haven't yet started on that one.

**Comment by MrYsLab** [comment]
I think this may be more complicated than I thought. Bleak is imported by one of the Adafruit modules. I am not sure how difficult this will be, but you might want to remove all the BLE code and leave the WiFi interface code. 
Essentially, look for
```
  if self.transport_is_wifi:
```
You would then need to substitute using a serial transport instead. 

I am unsure if this answers your question or not.

It may be simpler first to try the code using WiFi and see if it handles all of the traffic. I can run my ESP32 WiFi code while I am streaming video to 2 TVs in the house.

**Comment by MrYsLab** [comment]
Are you able to run the blink example for BLE? Either https://github.com/MrYsLab/telemetrix-esp32/blob/master/examples/ble-aio/blink_ble_aio.py or https://github.com/MrYsLab/telemetrix-esp32/blob/master/examples/ble/blink_ble.py?

**Comment by ipsod** [comment]
Hi Mr. Y.  I must admit, I was using a modified version of your library (Python and C), and I was hasty in assuming there was any problem with your code at all.  I tried using a (slightly) modified version before testing the base version at all, which, looking back, was silly.

I'm currently evaluating another library, and don't know if I'll try again with Telemetrix for this project.  However, if you think I may have uncovered some trouble, and you'd like me to investigate, then I will.

**Comment by MrYsLab** [comment]
Thanks. Good luck with your project.
